export interface Product{
    "internalCode": string;
    "name": string;
    "unit": string
    "unitType": string;
    "barcode": string;
    "price": string;
    "shelfLife": string;
    "shelfLifeType": string;
    "category": string
}

export const data:Product[] = [
    {
        "internalCode": "M1009",
        "name": "Full Cream Milk",
        "unit": "1",
        "unitType": "GALLON",
        "barcode": "6291031000198",
        "price": "20.13",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Fresh Milk"
    },
    {
        "internalCode": "M1006",
        "name": "Full Cream Milk",
        "unit": "2",
        "unitType": "LTR.",
        "barcode": "6291031000136",
        "price": "11.50",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Fresh Milk"
    },
    {
        "internalCode": "M1005",
        "name": "Full Cream Milk",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031000150",
        "price": "6.33",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Fresh Milk"
    },
    {
        "internalCode": "M1004",
        "name": "Full Cream Milk",
        "unit": "500",
        "unitType": "ML.",
        "barcode": "6291031000167",
        "price": "3.16",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Fresh Milk"
    },
    {
        "internalCode": "M1003",
        "name": "Full Cream Milk",
        "unit": "250",
        "unitType": "ML.",
        "barcode": "6291031000174",
        "price": "1.78",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Fresh Milk"
    },
    {
        "internalCode": "M1030",
        "name": "Low Fat Milk",
        "unit": "2",
        "unitType": "LTR.",
        "barcode": "6291031000235",
        "price": "11.50",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Fresh Milk"
    },
    {
        "internalCode": "M1029",
        "name": "Low Fat Milk",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031000259",
        "price": "6.33",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Fresh Milk"
    },
    {
        "internalCode": "",
        "name": "Low Fat Milk",
        "unit": "500",
        "unitType": "ML.",
        "barcode": "6291031000273",
        "price": "3.16",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Fresh Milk"
    },
    {
        "internalCode": "M1028",
        "name": "Low Fat Milk",
        "unit": "250",
        "unitType": "ML.",
        "barcode": "6291031000266",
        "price": "1.78",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Fresh Milk"
    },
    {
        "internalCode": "M1054",
        "name": "Skimmed Milk",
        "unit": "2",
        "unitType": "LTR.",
        "barcode": "6291031000334",
        "price": "11.50",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Fresh Milk"
    },
    {
        "internalCode": "M1053",
        "name": "Skimmed Milk",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031000358",
        "price": "6.33",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Fresh Milk"
    },
    {
        "internalCode": "M1051",
        "name": "Skimmed Milk",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031000365",
        "price": "1.78",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Fresh Milk"
    },
    {
        "internalCode": "M1403",
        "name": "Chocolate Milk",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031000457",
        "price": "6.33",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Flavored Milk"
    },
    {
        "internalCode": "M1402",
        "name": "Chocolate Milk",
        "unit": "500",
        "unitType": "ML.",
        "barcode": "6291031000495",
        "price": "3.16",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Flavored Milk"
    },
    {
        "internalCode": "M1401",
        "name": "Chocolate Milk",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031000471",
        "price": "1.55",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Flavored Milk"
    },
    {
        "internalCode": "M1428",
        "name": "Strawberry Milk",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031000556",
        "price": "6.33",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Flavored Milk"
    },
    {
        "internalCode": "M1427",
        "name": "Strawberry Milk",
        "unit": "500",
        "unitType": "ML.",
        "barcode": "6291031000594",
        "price": "3.16",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Flavored Milk"
    },
    {
        "internalCode": "M1426",
        "name": "Strawberry Milk",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031000570",
        "price": "1.6",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "Flavored Milk"
    },
    {
        "internalCode": "M1700",
        "name": "High Protein Milk",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031002567",
        "price": "9.50",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "High Protein Milk"
    },
    {
        "internalCode": "M1701",
        "name": "High Protein Milk",
        "unit": "300",
        "unitType": "ML.",
        "barcode": "6291031002574",
        "price": "4.50",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "High Protein Milk"
    },
    {
        "internalCode": "M1726",
        "name": "HP Chocolate",
        "unit": "300",
        "unitType": "ML.",
        "barcode": "6291031002819",
        "price": "4.50",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "High Protein Milk"
    },
    {
        "internalCode": "M1727",
        "name": "HP Strawberry",
        "unit": "300",
        "unitType": "ML.",
        "barcode": "6291031002826",
        "price": "4.50",
        "shelfLife": "5",
        "shelfLifeType": "DAYS",
        "category": "High Protein Milk"
    },
    {
        "internalCode": "M2008",
        "name": "Natural Yoghurt",
        "unit": "3.8",
        "unitType": "KG.",
        "barcode": "6291031020813",
        "price": "20.65",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2007",
        "name": "Natural Yoghurt",
        "unit": "2",
        "unitType": "KG.",
        "barcode": "6291031020912",
        "price": "12.65",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2005",
        "name": "Natural Yoghurt",
        "unit": "1",
        "unitType": "KG.",
        "barcode": "6291031020837",
        "price": "6.60",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2003",
        "name": "Natural Yoghurt",
        "unit": "400",
        "unitType": "GRAMS",
        "barcode": "6291031020028",
        "price": "3.00",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2002",
        "name": "Natural Yoghurt",
        "unit": "170",
        "unitType": "GRAMS",
        "barcode": "6291031020035",
        "price": "1.15",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2009",
        "name": "Natural Yoghurt",
        "unit": "100 x 6",
        "unitType": "GRAMS",
        "barcode": "2000003285129",
        "price": "5.10",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2001",
        "name": "Natural Yoghurt",
        "unit": "100",
        "unitType": "GRAMS",
        "barcode": "6291031020127",
        "price": "0.85",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2032",
        "name": "Low Fat Yoghurt",
        "unit": "2",
        "unitType": "KG.",
        "barcode": "6291031020134",
        "price": "12.65",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2030",
        "name": "Low Fat Yoghurt",
        "unit": "1",
        "unitType": "KG.",
        "barcode": "6291031020103",
        "price": "6.60",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2028",
        "name": "Low Fat Yoghurt",
        "unit": "400",
        "unitType": "GRAMS",
        "barcode": "6291031020059",
        "price": "3.00",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2027",
        "name": "Low Fat Yoghurt",
        "unit": "170",
        "unitType": "GRAMS",
        "barcode": "6291031020042",
        "price": "1.15",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2026",
        "name": "Low Fat Yoghurt",
        "unit": "100",
        "unitType": "GRAMS",
        "barcode": "6291031001546",
        "price": "0.92",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2033",
        "name": "Low Fat Yoghurt",
        "unit": "100 x 6",
        "unitType": "GRAMS",
        "barcode": "6291031001553",
        "price": "5.50",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2102",
        "name": "Labneh Regular",
        "unit": "400",
        "unitType": "GRAMS",
        "barcode": "6291031032557",
        "price": "7.45",
        "shelfLife": "15",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2101",
        "name": "Labneh Regular",
        "unit": "200",
        "unitType": "GRAMS",
        "barcode": "6291031032540",
        "price": "4.15",
        "shelfLife": "15",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2076",
        "name": "Sour Cream",
        "unit": "200",
        "unitType": "GRAMS",
        "barcode": "6291031032168",
        "price": "6.05",
        "shelfLife": "20",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2176",
        "name": "Fresh Cream",
        "unit": "100",
        "unitType": "GRAMS",
        "barcode": "6291031001775",
        "price": "2.88",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "M2178",
        "name": "Fresh Cream Lite",
        "unit": "100",
        "unitType": "GRAMS",
        "barcode": "6291031001782",
        "price": "2.88",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fresh Yoghurt"
    },
    {
        "internalCode": "",
        "name": "Zad Yoghurt",
        "unit": "4",
        "unitType": "KG.",
        "barcode": "6291031020165",
        "price": "17.00",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Catering Pack"
    },
    {
        "internalCode": "",
        "name": "Zad Yoghurt",
        "unit": "10",
        "unitType": "KG.",
        "barcode": "6291031020936",
        "price": "38.00",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Catering Pack"
    },
    {
        "internalCode": "",
        "name": "Chef Choice",
        "unit": "10",
        "unitType": "KG.",
        "barcode": "6291031002802",
        "price": "28.00",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Catering Pack"
    },
    {
        "internalCode": "",
        "name": "Sour Cream",
        "unit": "1",
        "unitType": "KG.",
        "barcode": "6291031032199",
        "price": "20.00",
        "shelfLife": "20",
        "shelfLifeType": "DAYS",
        "category": "Catering Pack"
    },
    {
        "internalCode": "",
        "name": "Labneh",
        "unit": "1",
        "unitType": "KG.",
        "barcode": "6291031032120",
        "price": "18.50",
        "shelfLife": "15",
        "shelfLifeType": "DAYS",
        "category": "Catering Pack"
    },
    {
        "internalCode": "M2903",
        "name": "Assorted Yoghurt",
        "unit": "125 X 6",
        "unitType": "GRAMS",
        "barcode": "6291031020387",
        "price": "7.50",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fruit Yoghurt"
    },
    {
        "internalCode": "M2648",
        "name": "Strawberry Yoghurt",
        "unit": "125",
        "unitType": "GRAMS",
        "barcode": "6291031020202",
        "price": "1.75",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fruit Yoghurt"
    },
    {
        "internalCode": "M2651",
        "name": "Strawberry Yoghurt",
        "unit": "125 X 6",
        "unitType": "GRAMS",
        "barcode": "6291031020400",
        "price": "10.00",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fruit Yoghurt"
    },
    {
        "internalCode": "M2618",
        "name": "Peach Yoghurt",
        "unit": "125",
        "unitType": "GRAMS",
        "barcode": "6291031020240",
        "price": "1.75",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fruit Yoghurt"
    },
    {
        "internalCode": "M2619",
        "name": "Peach Yoghurt",
        "unit": "125 X 6",
        "unitType": "GRAMS",
        "barcode": "6291031020424",
        "price": "10.00",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fruit Yoghurt"
    },
    {
        "internalCode": "M2633",
        "name": "Blueberry Yoghurt",
        "unit": "125",
        "unitType": "GRAMS",
        "barcode": "6291031020226",
        "price": "1.75",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fruit Yoghurt"
    },
    {
        "internalCode": "M2634",
        "name": "Blueberry Yoghurt",
        "unit": "125 X 6",
        "unitType": "GRAMS",
        "barcode": "6291031020417",
        "price": "10.00",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fruit Yoghurt"
    },
    {
        "internalCode": "M2678",
        "name": "Mango Yoghurt",
        "unit": "125",
        "unitType": "GRAMS",
        "barcode": "6291031020370",
        "price": "1.75",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fruit Yoghurt"
    },
    {
        "internalCode": "M2679",
        "name": "Mango Yoghurt",
        "unit": "125 X 6",
        "unitType": "GRAMS",
        "barcode": "6291031020455",
        "price": "10.00",
        "shelfLife": "14",
        "shelfLifeType": "DAYS",
        "category": "Fruit Yoghurt"
    },
    {
        "internalCode": "M3001",
        "name": "Laban Cool Natural 200ml. - Bottle",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031000921",
        "price": "1.15",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Laban Cool And Flavored"
    },
    {
        "internalCode": "M3005",
        "name": "Laban Cool Natural",
        "unit": "200 x 6",
        "unitType": "ML.",
        "barcode": "6291031000891",
        "price": "6.93",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Laban Cool And Flavored"
    },
    {
        "internalCode": "M3052",
        "name": "Laban Methi",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031000952",
        "price": "1.15",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Laban Cool And Flavored"
    },
    {
        "internalCode": "M3054",
        "name": "Laban Methi",
        "unit": "200 x 6",
        "unitType": "ML.",
        "barcode": "6291031000914",
        "price": "6.93",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Laban Cool And Flavored"
    },
    {
        "internalCode": "M3079",
        "name": "Laban Jeera",
        "unit": "2",
        "unitType": "LTR.",
        "barcode": "6291031000822",
        "price": "7.82",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Laban Cool And Flavored"
    },
    {
        "internalCode": "M3076",
        "name": "Laban Jeera",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031000969",
        "price": "1.15",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Laban Cool And Flavored"
    },
    {
        "internalCode": "M3080",
        "name": "Laban Jeera",
        "unit": "200 x 6",
        "unitType": "ML.",
        "barcode": "6291031000907",
        "price": "6.93",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Laban Cool And Flavored"
    },
    {
        "internalCode": "M3151",
        "name": "Laban Cool Mango",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031002888",
        "price": "1.15",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Laban Cool And Flavored"
    },
    {
        "internalCode": "M3171",
        "name": "Laban Cool Strawberry",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031002871",
        "price": "1.15",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Laban Cool And Flavored"
    },
    {
        "internalCode": "M3121",
        "name": "Traditional Laban",
        "unit": "2",
        "unitType": "LTR.",
        "barcode": "6291031001706",
        "price": "11.50",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Traditional Laban"
    },
    {
        "internalCode": "M3122",
        "name": "Traditional Laban",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031001713",
        "price": "6.33",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Traditional Laban"
    },
    {
        "internalCode": "M3123",
        "name": "Traditional Laban",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031001799",
        "price": "1.61",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Traditional Laban"
    },
    {
        "internalCode": "M3030",
        "name": "ProActiv Laban",
        "unit": "2",
        "unitType": "LTR.",
        "barcode": "6291031000730",
        "price": "11.50",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Proactiv Laban"
    },
    {
        "internalCode": "M3026",
        "name": "ProActiv Laban",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031000761",
        "price": "1.58",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Proactiv Laban"
    },
    {
        "internalCode": "M3027",
        "name": "ProActiv Laban",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031001591",
        "price": "1.58",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Proactiv Laban"
    },
    {
        "internalCode": "M5204",
        "name": "Orange Juice",
        "unit": "1.75",
        "unitType": "LTR.",
        "barcode": "6291031010029",
        "price": "8.00",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5203",
        "name": "Orange Juice",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031010050",
        "price": "4.50",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5202",
        "name": "Orange Juice",
        "unit": "500",
        "unitType": "ML.",
        "barcode": "6291031010067",
        "price": "2.60",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5201",
        "name": "Orange Juice",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031010104",
        "price": "1.25",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5135",
        "name": "Mango Juice",
        "unit": "1.75",
        "unitType": "LTR.",
        "barcode": "6291031002017",
        "price": "8.50",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5134",
        "name": "Mango Juice",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031002024",
        "price": "5.00",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5133",
        "name": "Mango Juice",
        "unit": "500",
        "unitType": "ML.",
        "barcode": "6291031002031",
        "price": "2.75",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5132",
        "name": "Mango Juice",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031002048",
        "price": "1.35",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5034",
        "name": "Fruit Cocktail",
        "unit": "1.75",
        "unitType": "LTR.",
        "barcode": "6291031002055",
        "price": "8.50",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5033",
        "name": "Fruit Cocktail",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031002062",
        "price": "5.00",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5032",
        "name": "Fruit Cocktail",
        "unit": "500",
        "unitType": "ML.",
        "barcode": "6291031002079",
        "price": "2.75",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5031",
        "name": "Fruit Cocktail",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031002086",
        "price": "1.35",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5004",
        "name": "Apple Juice",
        "unit": "1.75",
        "unitType": "LTR.",
        "barcode": "6291031010333",
        "price": "8.00",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5003",
        "name": "Apple Juice",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031010340",
        "price": "4.50",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5002",
        "name": "Apple Juice",
        "unit": "500",
        "unitType": "ML.",
        "barcode": "6291031010678",
        "price": "2.60",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5001",
        "name": "Apple Juice",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031010357",
        "price": "1.25",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5226",
        "name": "Mixed Berry",
        "unit": "1.75",
        "unitType": "LTR.",
        "barcode": "6291031002659",
        "price": "8.50",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5227",
        "name": "Mixed Berry",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031002666",
        "price": "5.00",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5228",
        "name": "Mixed Berry",
        "unit": "500",
        "unitType": "ML.",
        "barcode": "6291031002673",
        "price": "2.75",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M5229",
        "name": "Mixed Berry",
        "unit": "200",
        "unitType": "ML.",
        "barcode": "6291031002680",
        "price": "1.35",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Fresh Juice"
    },
    {
        "internalCode": "M2406",
        "name": "Greek Yoghurt",
        "unit": "360",
        "unitType": "GRAMS",
        "barcode": "6291031032229",
        "price": "8.84",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Greek Yoghurt And Flavored"
    },
    {
        "internalCode": "M2442",
        "name": "Apple Cinnamon Greek Yoghurt.",
        "unit": "360",
        "unitType": "GRAMS",
        "barcode": "6291031002796",
        "price": "8.84",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Greek Yoghurt And Flavored"
    },
    {
        "internalCode": "M2452",
        "name": "Blueberry Greek Yoghurt",
        "unit": "360",
        "unitType": "GRAMS",
        "barcode": "6291031000747",
        "price": "8.84",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Greek Yoghurt And Flavored"
    },
    {
        "internalCode": "M2422",
        "name": "Mango Greek Yoghurt 360g.",
        "unit": "360",
        "unitType": "GRAMS",
        "barcode": "6291031002772",
        "price": "8.84",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Greek Yoghurt And Flavored"
    },
    {
        "internalCode": "M2432",
        "name": "Strawberry Greek Yoghurt 360g.",
        "unit": "360",
        "unitType": "GRAMS",
        "barcode": "6291031000693",
        "price": "8.84",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Greek Yoghurt And Flavored"
    },
    {
        "internalCode": "M2405",
        "name": "Greek Yoghurt Regular 150g.",
        "unit": "150",
        "unitType": "GRAMS",
        "barcode": "6291031032236",
        "price": "4.06",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Greek Yoghurt And Flavored"
    },
    {
        "internalCode": "M2441",
        "name": "Apple Cinnamon Greek",
        "unit": "150",
        "unitType": "GRAMS",
        "barcode": "6291031002789",
        "price": "4.06",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Greek Yoghurt And Flavored"
    },
    {
        "internalCode": "M2451",
        "name": "Blueberry Greek Yoghurt",
        "unit": "150",
        "unitType": "GRAMS",
        "barcode": "6291031000792",
        "price": "4.06",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Greek Yoghurt And Flavored"
    },
    {
        "internalCode": "M2421",
        "name": "Mango Greek Yoghurt",
        "unit": "150",
        "unitType": "GRAMS",
        "barcode": "6291031002765",
        "price": "4.06",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Greek Yoghurt And Flavored"
    },
    {
        "internalCode": "M2431",
        "name": "Strawberry Greek Yoghurt",
        "unit": "150",
        "unitType": "GRAMS",
        "barcode": "6291031000709",
        "price": "4.06",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Greek Yoghurt And Flavored"
    },
    {
        "internalCode": "M2501",
        "name": "Drinking Greek Yoghurt",
        "unit": "300",
        "unitType": "ML.",
        "barcode": "6291031002598",
        "price": "5.51",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Drinking Greek Yoghurt"
    },
    {
        "internalCode": "M2502",
        "name": "Strawberry Greek Yoghurt",
        "unit": "300",
        "unitType": "ML.",
        "barcode": "6291031002611",
        "price": "5.51",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Drinking Greek Yoghurt"
    },
    {
        "internalCode": "M2503",
        "name": "Blueberry Greek Yoghurt",
        "unit": "300",
        "unitType": "ML.",
        "barcode": "6291031002604",
        "price": "5.51",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Drinking Greek Yoghurt"
    },
    {
        "internalCode": "M2505",
        "name": "Apple And Cinnamon With Oats",
        "unit": "300",
        "unitType": "ML.",
        "barcode": "6291031002628",
        "price": "5.51",
        "shelfLife": "10",
        "shelfLifeType": "DAYS",
        "category": "Drinking Greek Yoghurt"
    },
    {
        "internalCode": "M5901",
        "name": "Assorted Juice",
        "unit": "1.75 Ltr X 2",
        "unitType": "LTR.",
        "barcode": "2000008174411",
        "price": "14.00",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Promotion Items"
    },
    {
        "internalCode": "M5902",
        "name": "Assorted Juice",
        "unit": "1 X 3",
        "unitType": "LTR.",
        "barcode": "6291031010821",
        "price": "11.50",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Promotion Items"
    },
    {
        "internalCode": "M5904",
        "name": "Assorted Juice",
        "unit": "500 x 3",
        "unitType": "ML.",
        "barcode": "6291031002727",
        "price": "6.00",
        "shelfLife": "30",
        "shelfLifeType": "DAYS",
        "category": "Promotion Items"
    },
    {
        "internalCode": "M7000",
        "name": "Uht Full Fat Milk 1 Ltr",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031001195",
        "price": "5.17",
        "shelfLife": "6",
        "shelfLifeType": "MONTHS",
        "category": "Uht Milks (Long Life)"
    },
    {
        "internalCode": "M7026",
        "name": "Uht Full Fat Milk 1 Ltr X 4",
        "unit": "1 x 4",
        "unitType": "LTR.",
        "barcode": "6291031001218",
        "price": "20.68",
        "shelfLife": "6",
        "shelfLifeType": "MONTHS",
        "category": "Uht Milks (Long Life)"
    },
    {
        "internalCode": "",
        "name": "Full Cream Milk",
        "unit": "1 x 12",
        "unitType": "LTR.",
        "barcode": "6291031001188",
        "price": "62.04",
        "shelfLife": "6",
        "shelfLifeType": "MONTHS",
        "category": "Uht Milks (Long Life)"
    },
    {
        "internalCode": "",
        "name": "Uht Low Fat Milk",
        "unit": "1",
        "unitType": "LTR.",
        "barcode": "6291031001232",
        "price": "5.17",
        "shelfLife": "6",
        "shelfLifeType": "MONTHS",
        "category": "Uht Milks (Long Life)"
    },
    {
        "internalCode": "M7032",
        "name": "Marmum Uht Low Fat Milk 1 Ltr X 4",
        "unit": "1X4",
        "unitType": "LTR.",
        "barcode": "6291031001249",
        "price": "20.68",
        "shelfLife": "6",
        "shelfLifeType": "MONTHS",
        "category": "Uht Milks (Long Life)"
    },
    {
        "internalCode": "M7031",
        "name": "Low Fat Milk 1ltr. X 12",
        "unit": "12",
        "unitType": "LTR.",
        "barcode": "6291031001225",
        "price": "62.04",
        "shelfLife": "6",
        "shelfLifeType": "MONTHS",
        "category": "Uht Milks (Long Life)"
    },
    {
        "internalCode": "M7032",
        "name": "Mozzarella Cheese",
        "unit": "500",
        "unitType": "GRAMS",
        "barcode": "6291031001836",
        "price": "17.50",
        "shelfLife": "6",
        "shelfLifeType": "MONTHS",
        "category": "Cheese Item"
    },
    {
        "internalCode": "M7031",
        "name": "Mozzarella Cheese",
        "unit": "200",
        "unitType": "GRAMS",
        "barcode": "6291031001829",
        "price": "7.50",
        "shelfLife": "6",
        "shelfLifeType": "MONTHS",
        "category": "Cheese Item"
    },
    {
        "internalCode": "M7033",
        "name": "Shredded Mozzarella",
        "unit": "700",
        "unitType": "GRAMS",
        "barcode": "6291031002857",
        "price": "19.00",
        "shelfLife": "6",
        "shelfLifeType": "MONTHS",
        "category": "Cheese Item"
    },
    {
        "internalCode": "M7034",
        "name": "Shredded Mozzarella Cheese",
        "unit": "400",
        "unitType": "GRAMS",
        "barcode": "6291031002864",
        "price": "11.00",
        "shelfLife": "6",
        "shelfLifeType": "MONTHS",
        "category": "Cheese Item"
    }
];